# Generated by Django 2.0.3 on 2018-08-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0064_productvariant_handle_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='links', to='product.Product')),
            ],
            options={
                'permissions': (('view', 'Can view linked products'), ('edit', 'Can edit linked products')),
            },
        ),
    ]
